/* Generated by vala-dbus-binding-tool 1.0-aa2fb. Do not modify! */
/* Generated with: vala-dbus-binding-tool --api-path=src/dbus/upower.xml */
using GLib;

namespace org {

	namespace freedesktop {

		namespace DBus {

			[DBus (name = "org.freedesktop.DBus.Peer", timeout = 120000)]
			public interface Peer : GLib.Object {

				[DBus (name = "Ping")]
				public abstract void ping() throws DBusError, IOError;

				[DBus (name = "GetMachineId")]
				public abstract string get_machine_id() throws DBusError, IOError;
			}

			[DBus (name = "org.freedesktop.DBus.Peer", timeout = 120000)]
			public interface PeerSync : GLib.Object {

				[DBus (name = "Ping")]
				public abstract void ping() throws DBusError, IOError;

				[DBus (name = "GetMachineId")]
				public abstract string get_machine_id() throws DBusError, IOError;
			}

			[DBus (name = "org.freedesktop.DBus.Introspectable", timeout = 120000)]
			public interface Introspectable : GLib.Object {

				[DBus (name = "Introspect")]
				public abstract string introspect() throws DBusError, IOError;
			}

			[DBus (name = "org.freedesktop.DBus.Introspectable", timeout = 120000)]
			public interface IntrospectableSync : GLib.Object {

				[DBus (name = "Introspect")]
				public abstract string introspect() throws DBusError, IOError;
			}

			[DBus (name = "org.freedesktop.DBus.Properties", timeout = 120000)]
			public interface Properties : GLib.Object {

				[DBus (name = "Get")]
				public abstract GLib.Variant get(string interface_name, string property_name) throws DBusError, IOError;

				[DBus (name = "GetAll")]
				public abstract GLib.HashTable<string, GLib.Variant> get_all(string interface_name) throws DBusError, IOError;

				[DBus (name = "Set")]
				public abstract void set(string interface_name, string property_name, GLib.Variant value) throws DBusError, IOError;

				[DBus (name = "PropertiesChanged")]
				public signal void properties_changed(string interface_name, GLib.HashTable<string, GLib.Variant> changed_properties, string[] invalidated_properties);
			}

			[DBus (name = "org.freedesktop.DBus.Properties", timeout = 120000)]
			public interface PropertiesSync : GLib.Object {

				[DBus (name = "Get")]
				public abstract GLib.Variant get(string interface_name, string property_name) throws DBusError, IOError;

				[DBus (name = "GetAll")]
				public abstract GLib.HashTable<string, GLib.Variant> get_all(string interface_name) throws DBusError, IOError;

				[DBus (name = "Set")]
				public abstract void set(string interface_name, string property_name, GLib.Variant value) throws DBusError, IOError;

				[DBus (name = "PropertiesChanged")]
				public signal void properties_changed(string interface_name, GLib.HashTable<string, GLib.Variant> changed_properties, string[] invalidated_properties);
			}
		}
	}
}
